### ISSUE TITLE
Отчет

### ISSUE THREAD

**Issue by saburovatory** [saburovatory/Cryptography#2]
@ioannkozlitin , 

> Латинизировать весь вывод в консоль (у меня проблемы с кодировкой под linux)

Выполнено
> Структурировать код (разбить на функции с читаемыми именами и понятным назначением)

Выполнено
> Вместо файлов с 0 и 1 из этих 0 и 1 вновь собирать символы (5-битная кодировка) и в таком виде выводить

Почему 5-битная кодировка? Ведь у нас 26 заглавных и 26 строчных букв + пробел = 53 символа. Итого нам нужна минимум 6 - битная кодировка (2^6=64). 
Нет ли смысла оставить 8 - битную ? Файл выхода будет весить НЕМНОГО меньше, но ведь затрат по времени станет больше.
> С гистограммами пока ничего нового не делайте, сосредоточьтесь на первых 3 пунктах

ОК
> Пишите лучше все сюда, отчеты тоже сюда

ОК

**Comment by ioannkozlitin** [comment]
Я думал, что большие и малые буквы не различаются, тогда 5 бит. 6-ти (или 5-ти) битная кодировка лучше 8-битной, так как уменьшает избыточность, что очень важно для нашей задачи. Дело не в размере. Как альтернатива можно прогнать выход шифратора через арифметический кодер или хафмана, но тогда при дешифрации придется делать обратное преобразование, что неудобно. По той же причине большие и малые буквы лучше не различать.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Выполнено последнее замечание.
- 5 - битная кодировка
- большие буквы не различаются с маленькими

**Comment by ioannkozlitin** [comment]
Хорошо, что дело движется. Есть несколько замечаний:

1. Уменьшите размер Вашего открытого текста до 1 предложения из исходного текста, т.к. в нынешнем виде из-за огромного размера открытого текста сложно анализировать работу программы, особенно учитывая, что весь текст вытягивается в 1 строчку. Построения гистограмм это замечание не касается - там как раз надо текста побольше.

2. Файл бинарной гистограммы должен быть существенно больше, а не состоять из одной строчки - видимо какая-то ошибка в коде.

3. Шифрованный файл должен состоять из тех же символов, что и шифруемый, т.е. из малых латинских букв и пробелов (и еще из некоторых других символов, о чем ниже). Поэтому в выходной файл надо писать САМИ СИМВОЛЫ, А НЕ ИХ КОДЫ, т.е., например, пробел для 0, 'a' для 1,  'b' для 2 ... 'z' для 26. Поскольку коды 27..31 не имеют символов, следует дополнить число символов до 32, например, добавив знаки препинания, символы перевода строки и т.п. Естественно, тогда и при выбрасывании символов надо оставить в тексте знаки препинания, символы перевода строки ... и все то, что Вы решите туда добавить.

p.s. Постарайтесь с этим разобраться дня за 3. Лучше сначала напрячься, а потом отдыхать, чем наоборот, когда будет время поджимать.

**Comment by ioannkozlitin** [comment]
Посмотрев внимательнее понял, что у Вас в шифрованный файл пишутся не коды, а что-то более хитрое, но что конкретно происходит я с наскока понять не смог - надо ковыряться в Вашем коде. Это, похоже, ближе к истине, но все-же не совсем то. Чтобы хотелось бы видеть, я написал в 3 пункте выше. Если все равно не понятно, то пишите сюда, попробуем разобраться.

**Comment by saburovatory** [comment]
Доброе утро, Иван Алексеевич!Комментарии поняла, постараюсь как можно скорее разобраться .--Отправлено из мобильной Яндекс.Почты23.01.2017, 10:39, "ioannkozlitin" <notifications@github.com>:Посмотрев внимательнее понял, что у Вас в шифрованный файл пишутся не коды, а что-то более хитрое, но что конкретно происходит я с наскока понять не смог - надо ковыряться в Вашем коде. Это, похоже, ближе к истине, но все-же не совсем то. Чтобы хотелось бы видеть, я написал в 3 пункте выше. Если все равно не понятно, то пишите сюда, попробуем разобраться.

**Comment by saburovatory** [comment]
Хотел бы прояснить пункт три
Кодирование 
1.Наш файл переводим в последовательность нулей и единиц 
2. Берём ключ 
3. XOR-им
4. Получаем новую последовательность нулей и единиц
5. Каждые 5 бит - Новый символ - что и выводится в файл
Декорирование 
6. Переводим шифрованный файл в последовательность нулей и единиц
7. Берём ключ
8. XOR -им с ключом
9. Старая последовательность нулей и единиц, где каждые пять бит-наша буква из исходного файла.
Понятно, что до 32 можно добавить знаки препинания и тд. Но после xor-а мы можем получить код больше 32, и тогда символом может быть не только буква.

**Comment by saburovatory** [comment]
@ioannkozlitin
Оставила комментарий выше

**Comment by ioannkozlitin** [comment]
Если xor-рить поразрядно 5-битные значения, то в результате никак больше 31 не получишь, разве не так?

**Comment by ioannkozlitin** [comment]
Можете завтра в 15.00 прийти на консультацию, если Вам это необходимо.

**Comment by saburovatory** [comment]
Подойти я точно не смогу.

**Comment by saburovatory** [comment]
То есть таким образом получается что процедура шифрования происходит неверно? Потому что есть символы отличные от букв

**Comment by ioannkozlitin** [comment]
А почему неверно? В шифротексте и должен быть всякий бред. Что смущает?

**Comment by saburovatory** [comment]
Да, но получается если до 32, то например символа '>' или '$' не должно быть?

**Comment by ioannkozlitin** [comment]
Некоторые другие символы - это и есть те, что с кодами 27 по 31.

**Comment by ioannkozlitin** [comment]
Получается так. Поэтому я все это и написал.

**Comment by saburovatory** [comment]
Не совсем понимаю просто тогда третий пункт; получается у меня с 27 по 31 заполнено случайными символами, а необходимы адекватные знает препинания?

**Comment by saburovatory** [comment]
*знаки

**Comment by ioannkozlitin** [comment]
Да, надо так. И при кодировании знаки препинания заменять на эти коды.

**Comment by saburovatory** [comment]
"Ну Семен Семеныч...." - если Вы знаете эту цитату:)
я поняла Вас, спасибо:)

**Comment by ioannkozlitin** [comment]
Слышал...

**Comment by ioannkozlitin** [comment]
Вот Вам тест на правильность: если зашифровать шифротекст с тем же ключом, что и при первом шифровании, то должен получиться открытый текст :). Это следует из свойств XOR. Поэтому дешифратор сам по себе вообще не нужен.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, добавились символы в алфавит (27-31);
Декодируется верно;
В кодированном файле как и ожидалось, ерунда, то есть все верно.

**Comment by ioannkozlitin** [comment]
1. Вы попробовали двойное шифрование с одним ключом?
2. Вы проигнорировали мое замечание насчет размера шифруемого текста. Оставьте, пожалуйста, ОДНО ПРЕДЛОЖЕНИЕ. Очень неудобно анализировать результат работы.
3. С гистограммой, вроде, все теперь хорошо.

**Comment by ioannkozlitin** [comment]
Для удобства дальнейшей работы сделайте, чтобы программу можно было запускать из командной строки, например, так:

Cryptography key.txt input.txt crypt.txt

key.txt содержит начальное значение регистра, т.е. то, что стоит справа в операторе
static unsigned long S = 0x00000001; (в данном случае 1)

input.txt - файл со всеми возможными символами
crypt.txt - шифротекст

Понятно, что названия файлов могут быть и другими.

Тогда если сделать

Cryptography key.txt input.txt crypt.txt
Cryptography key.txt crypt.txt crypt2.txt

то файл crypt2.txt должен содержать осмысленный текст, а если в input.txt есть только
"разрешенные" символы, то просто должен с ним совпадать.

P.S. Если все отлажено, то необязательно сбрасывать на диск промежуточные файлы.

**Comment by saburovatory** [comment]
@ioannkozlitin
Хорошо, я поняла
А будут какие- то задачи а доработку самого функционала программы, и тд?

**Comment by ioannkozlitin** [comment]
Будут, когда будет уверенность, что все работает правильно. Я думаю это будет уже скоро :)

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, доброе утро.
Хотела предупредить о паре вещей
1) запуск из консоли доделаю к концу этой недели (завтра - после завтра)
2) следующий коммит смогу добавить в 20-ых числах февраля, так как уезжаю.
3) не смотря на то, что функционал программы мы будем дорабатывать после того, как удостоверимся, что все работает верно, я бы хотела получить все же некий план; мне тяжеловато работать абстрактно
Например, после того как все заработает, необходимо добавить графики -> усложнить процедуру шифрования -> ... -> написать документацию.
Что - то в таком духе. Была бы признательна, за такое краткое, но все же описание.

**Comment by ioannkozlitin** [comment]
1. Добиться правильной работы того, что есть. Если Вы немного ускоритесь, то мы сможем сделать это до Вашего отъезда.

2. Реализовать простой перебор ключей с критерием на открытый текст на основе последовательного анализа Вальда при априори известной гистограмме открытого текста (про последовательный анализ можете почитать уже сейчас).

3. Реализовать критерий на основе запрещенных биграмм.

4. Реализовать критерий на основе ансамбля простых критериев запрещенных биграмм с разной структурой - линеной, древовидной и т.п.

5. Реализовать критерий на основе рандомизированного леса.

6. Рассмотреть возможность применения наработанных методик к более "мирным" приложениям - распознванию кодировок, типов файлов, авторства текстов и т.п.

7. Написание диплома (впрочем писать можно начать уже сейчас, например, обзорную часть).

Примерно так. Работы много, а времени мало, так что не тяните.
 
Успехов!

**Comment by saburovatory** [comment]
@ioannkozlitin 
Спасибо большое!
Можете сказать, где почитать про 2, чтобы иметь понимание как делать.

**Comment by saburovatory** [comment]
После последнего комита, думаю целесообразно открыть новый issue, так как переписка стала великовата.

**Comment by ioannkozlitin** [comment]
Добавил книгу по статистике. В ней можете посмотреть.

**Comment by ioannkozlitin** [comment]
Вы вернулись? Отдохнули? Готовы трудиться над дипломом?

1 февр. 2017 г. 16:35 пользователь "saburovatory" <notifications@github.com>
написал:

**Comment by saburovatory** [comment]
@ioannkozlitin
Иван Алексеевич, давайте писать в третье ишью
