### ISSUE TITLE
Новый этап

### ISSUE THREAD

**Issue by ioannkozlitin** [saburovatory/Cryptography#3]
Задание на будующее:
    1. Реализовать простой перебор ключей с критерием на открытый текст на основе последовательного анализа Вальда при априори известной гистограмме открытого текста (про последовательный анализ можете почитать уже сейчас).
    2. Реализовать критерий на основе запрещенных биграмм.
    3. Реализовать критерий на основе ансамбля простых критериев запрещенных биграмм с разной структурой - линеной, древовидной и т.п.
    4. Реализовать критерий на основе рандомизированного леса.
    5. Рассмотреть возможность применения наработанных методик к более "мирным" приложениям - распознванию кодировок, типов файлов, авторства текстов и т.п.
    6. Написание диплома (впрочем писать можно начать уже сейчас, например, обзорную часть).

Примерно так. Работы много, а времени мало, так что не тяните.

Успехов!

**Comment by ioannkozlitin** [comment]
В вашей проге были мелкие косячки. Я тут немного ее отладил, теперь все правильно работает. Тест с двойным шифрованием проходит хорошо. Задание см. выше. Впрочем я уже это раньше писал.

P.S. Первое что надо сделать - отказаться от промежуточных файлов и делать все в памяти, поскольку для перебора ключей потребуется экстремально высокая производительность шифрования, а с файлами ее не получить.

**Comment by ioannkozlitin** [comment]
Суть того, что я Вам пытался донести по телефону:

1. У вас все и так  хорошо, не волнуйтесь.
2. Если Вы постараетесь побольше, то вместо хорошей работы у Вас получится отличная, и Вы сами будете гордиться тем, какой большой путь и какую трудную работу Вы сделали.
3. Если Вам не особо нравится работать из-под палки (а диплом это, конечно, в некотором роде работа из-под палки), то превратите это в удовольствие. А чтобы это приносило удовольствие, надо вложить в это ваши силы, время, фантазию, в общем все, чем вы владете. Работайте неформально, не для галочки.

P.S. Пока отдыхайте, а потом с 20 числа с новыми силами принимайтесь за дело. У Вас все получится.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, подскажите по поводу первого задания.
вот презентация, которую я нашла
http://www.machinelearning.ru/wiki/images/b/b2/Lec5.pdf
Но не могли бы Вы все - таки дать немного комментариев по поводу решения данной задачи, чтобы мне побыстрее начать реализацию.

И еще напоминаю Вам по "рыбу" самого диплома, про которую Вам сегодня по телефону сказала.
Спасибо! Жду ответа.

**Comment by ioannkozlitin** [comment]
У нас 2 гипотезы:

1. Основная - текст открытый. В нем биграммы распределены в соответствии с известной нам априори гистограммой (считаем заранее по всему тексту).
2. Альтернативная - текст шифрованный. В нем все биграммы равновероятны.

Далее составляем отношение правдоподобия.
Пусть мы имеем строку символов: abdbrsa...

Тогда отношение правдоподобия на 1 шаге p(ab)/p0, на 2 шаге p(ab)*p(bd)/p0^2 ... на 6 шаге
r = p(ab)*p(bd)*p(db)*p(br)*p(rs)*p(sa) / p0^6 

Здесь p0 - вероятность биграммы при равномерном распределении, в нашем случае p0=1/32^2 = 1/1024, т.к. у нас алфавит из 32 символов.

Можно в логарифмической форме ln(r) = ln(p(ab)) + ln(p(bd)) + ... + ln(p(sa)) - 6 * ln(p0). Это удобнее, так как поможет избежать переполнения при длинных цепочках символов. 

Потом ставим 2 порога - верхний и нижний. Если выше верхнего - открытый текст, ниже нижнего - шифрованный, если между - продолжаем расшифровывать. Как по-умному подбирать пороги - пока не знаю, но, думаю, проще это сделать экспериментально.

Если непонятно, то пишите, в чем конкретно затык. Чем четче и подробнее Вы его опишите, тем легче мне будет Вам ответить.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, произошел следующий затык.
Если мы берем, например, большую выборку, где есть биграмма ab, то при делении количества данной биграммы на количество биграмм во всем тексте получается слишком маленькое число.
Тогда при умножении мы получаем слишком маленькое отношение правдоподобия r, которое на длинных последовательностях превращается  в ноль... Что делать ? :)

Второй вопрос от лица ваших подопечных. Не могли бы Вы выслать мне, Владиславу, Павлу, Артему сформулированные темы дипломных работ. Это как всегда требуется для написания бумаг, которые мы бы потом принесли Вам на подпись. Там все просто, нужна только тема (само название); мы заполним как обычно, и Вам донесем, чтоб сдать это на кафедре.

**Comment by ioannkozlitin** [comment]
Надо переходить к логарифмическому отношению правдоподобия, о чем я писал выше, т.е. вместо r вычислять ln(r). А темы я, кажется, всем уже сформулировал, разве нет?

**Comment by saburovatory** [comment]
Моя тема сформулирована как "Распознование слов после шифрования"?

**Comment by saburovatory** [comment]
@ioannkozlitin
Не указала логин в предыдущем сообщении

**Comment by saburovatory** [comment]
Здесь даже больше не о теме, а формулировке названия ВКР

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич,
при подстановке логарифма сумма все равно получается отрицательной, то есть из-за маленьких чисел, логарифмы отрицательные, и в сумме получается  -inf.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, добавила черновик диплома в проект 
Главы и Части я взял из письма, которое Вы присылали в октябре. Может его стоит обновить?
Написала введение на работу. Хотелось бы услышать комментарии - больше или меньше нужны, чем расширить и т.д.
Хотела бы начать писать первую часть, там где мы использовали примитивный многочлен. Но тогда я не совсем понимаю, куда это втыкать, и плюс к этому, если оставить первую часть про изучение базовых понятий -  тогда эту часть тоже возьму в работу.

Я буду вести работу над программой и текстовой частью параллельно, скидывая Вам отчет до текстовой части раз в неделю, а на буднях буду заниматься реализацией - это чтобы Вы  были в курсе, что и когда от меня примерно ожидать. 
Текстовая часть отнимает много времени, я бы не хотела в мае хвататься за голову и копировать статьи из википедии для ее наполнения:)

**Comment by saburovatory** [comment]
Добавлю еще, что возможно после написания первых двух частей возможно можно будет сделать публикацию. Но это конечно сейчас не к спеху.

**Comment by ioannkozlitin** [comment]
Тема та же, что и для предипломной практики. Посмотрите старую переписку. По сути буду завтра смотреть, т.к. в выходные нет времени на это. Насчет inf у вас там где-то чистый 0 попадается, я думаю.

**Comment by ioannkozlitin** [comment]
Нашел в недрах своей почты: Критерий на открытый текст на базе решающего леса

**Comment by ioannkozlitin** [comment]
План диплома вполне приличный, хотя потом, возможно, надо будет его откорректировать. Только не пишите "Изучение базовых понятий криптографии", а напишите лучше "Базовые понятия криптографии" и все в таком роде. 

По поводу 0 результата: если получили на каком-то шаге 0 или (-inf), то этот текст явно не открытый, т.к. встретилась биграмма, которой нет в нашей статистике по биграммам (это и есть "запрещенная" биграмма).

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алекссевич, добавила коммит последний
Посмотрите, пожалуйста, почему выходит ноль, не могу разобраться

**Comment by ioannkozlitin** [comment]
Завтра гляну, чего там происходит у Вас...

**Comment by ioannkozlitin** [comment]
Даже не запуская, могу сделать ряд замечаний:

1. Гистограмму биграмм надо строить по ВСЕМУ БОЛЬШОМУ ФАЙЛУ, который у Вас был сначала.
2. Надо переходить к логарифмам
3. Ноль в случае с логарифмами может встретиться только если mp2.find(sec)->second == 0. Этот случай надо обрабатывать отдельно. Ясно, что после 0 чтобы там дальше не было, можно сразу сказать, что отношение равно 0 и текст открытым не является.

Можно и немного иначе:

double r = 0;
...
r = r + log(std::max(mp2.find(sec)->second/1024.0, 1e-308));//то есть заменям ноль на 1e-308
...

return r - (symbols_count - 1) * log(p0);//не очень понимаю, почему в Вашем тексте написано symbols_count/1024.0, зачем делить на 1024? Единицу отнимаем, потому что биграмм на 1 меньше, чем символов.

Дальше анализируем уже log(r).

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, добавила последний коммит с выводом коэффициента правдоподобия. Не знаю какой порог будет с переходе от шифрованного к нешифрованному, но запуская, получала что шифрованный текст дает результат до 35 примерно. Как здесь получить это число? Или можно оставить примерно так?

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, посмотрите еще, пожалуйста, текстовый документ с теоретическим обоснованием (прикреплен к проекту VKR_Saburova_VP_40) - написано введение и первая часть.
Хотела бы получить толчок дальше  -комментарии, тезисы о следующей главе.
Спасибо!

**Comment by ioannkozlitin** [comment]
35 - это log(r) или сам r? На открытом тексте запускать пробовали?

**Comment by ioannkozlitin** [comment]
По тексту: надо поправить оглавление. Далее: текст 1 части 1 главы, начиная с "Учитывая все вышесказанное, можем..." просится в начало, а закончить лучше РСЛОС с его преимуществами и недостатками.

Еще: "текст для дешифрования", как мне кажется, не может быть открытым по определению. Другое дело, "текст, получающийся в результате дешифрования".

Следовало написать, что в открытом тексте "биграммы ... распределены в соответствии с априори известной гистограммой", а в шифрованном "все биграммы равновероятны".

**Comment by saburovatory** [comment]
@ioannkozlitin 
Это log(r)
Да, пробовала
Примерно 170, если брать одно предложение. Чем больше выборка соотственно тем больше число. Если брала прямо главу, выходило 6000 и так далее

Про текст поняла, поправлю, залью

**Comment by ioannkozlitin** [comment]
Исправил у Вас ошибочку: вместо return 0; надо добавлять к log(r) логарифм очень маленького числа (в идеале 0, но тогда будет переполнение). Еще: вы уверены, что общее число биграмм в вашей статистике равно symbols_count/5 - 1.0 ? Проверьте.

**Comment by saburovatory** [comment]
@ioannkozlitin
Иван Алексеевич, такой вопрос
Если у нас результат ноль ( применяв к шифрованному тексту) - мы же можем сразу сказать, что он шифрованный? Как Вы и писали ранее

То есть
Я беру предложения из шифрованного текста, прогоняю их и могу получить:
1) 0 - текст шифрованный 100%
2) некий порог, по которому могу сказать, что < текст шифрованный, > открытый текст

**Comment by saburovatory** [comment]
Или мы шифруем только по биграммам из исходного текста?

**Comment by ioannkozlitin** [comment]
Если 0 - значит попалась биграмма, которой нет в статистке, так что да, шифрованный. А вот 2 Ваш вопрос я не понял, поясните, пожалуйста.

**Comment by ioannkozlitin** [comment]
Только 0 - это r = 0 или log(r) = -inf

**Comment by ioannkozlitin** [comment]
У Вальда 2 порога: > верхнего - точно открытый, < нижнего - точно шифрованный, в промежутке берем очередной символ и считаем отношение, пока не выскочим из этого промежутка.

**Comment by saburovatory** [comment]
@ioannkozlitin 
то есть может быть такое, что мы попадем в промежуток?
Теперь поняла; то есть  у нас , грубо говоря, три отрезка:
[0;х1] - точно шифрованный
[х1;х2] - беерм символ, пока не выйдем из промежутка
[х2; inf] - открытый
и теперь я ищу границы

**Comment by ioannkozlitin** [comment]
Да, все верно.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, немного по тексту

> По тексту: надо поправить оглавление. Далее: текст 1 части 1 главы, начиная с "Учитывая все вышесказанное, можем..." просится в начало, а закончить лучше РСЛОС с его преимуществами и недостатками. 
- оглавление - если Вы имели в виду стили, пока не правила, там что - то не так, пока не понимаю что, буду исправлять в целом форматирование позже. Если имелась в виду содержательная часть - тогда не поняла, о чем Вы.

> Еще: "текст для дешифрования", как мне кажется, не может быть открытым по определению. Другое дело, "текст, получающийся в результате дешифрования".
 -здесь исправила

> Следовало написать, что в открытом тексте "биграммы ... распределены в соответствии с априори известной гистограммой", а в шифрованном "все биграммы равновероятны".
- Такое в тексте было, возможно, Вы не заметили - в самом конце введения. Либо мы друг друга не поняли.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич
Присылаю сюда данные
Сначала текст, у которого считаем коэффициент правдоподобия, затем сам коэффициент

Сначала открытый, затем шифрованный
Даю ссылку гугл док, туда внесла все результаты
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit?usp=sharing

**Comment by ioannkozlitin** [comment]
С текстом стало лучше, практически все исправили, хотя смотрел по диагонали. Еще: у меня ученая степень к.ф.-м.н., а не к.т.н.

**Comment by ioannkozlitin** [comment]
Результаты Ваши посмотрел. Хорошо бы теперь построить распределение (гистограмму) отношения правдоподобия при разных фиксированных длинах текста, откртытого и шифрованного, тогда будет яснее, как порог ставить. Т.е. берем, например, 3 символа из разных мест текста. Считаем каждый раз отношение правдоподобия и строим гистограмму. Такую же гистограмму можно для 4 символов построить, для 5 и т.п.

**Comment by saburovatory** [comment]
> С текстом стало лучше, практически все исправили, хотя смотрел по диагонали. Еще: у меня ученая степень к.ф.-м.н., а не к.т.н.

прошу прощения, не уточнила, забыла. Исправлю

>  Т.е. берем, например, 3 символа из разных мест текста. Считаем каждый раз отношение правдоподобия и строим гистограмму. Такую же гистограмму можно для 4 символов построить, для 5 и т.п

поняла. Попробую.
