### ISSUE TITLE
Продолжение работы

### ISSUE THREAD

**Issue by saburovatory** [saburovatory/Cryptography#4]
@ioannkozlitin 
Иван Алексеевич, добавила в код вывод гистограмм
Сейчас необходимо вручную ввести название файла (открытого или шифрованного), будет выводится количество символов и отношение.
Оставила изменения в том же файле
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit

**Comment by ioannkozlitin** [comment]
Я посмотрел результат, но не понял, что содержится во 2 колонке каждого столбца таблицы - отношение правдоподобия для какого-то одного текста заданной длинны, или среднее отношение правдоподобия по многим текстам? Нужно именно последнее, причем не только среднее, но и стандартное отклонение.

**Comment by saburovatory** [comment]
@ioannkozlitin 
2 - 2.44998
2 - длина текста,
2.44998 - отношение правдоподобия для заданной длины
Что означает отношение правдоподобия по многим текстам? То есть нужно суммировать все тексты, или каждый раз брать разные тексты длины "2", находить среднее значение отношения правдоподобия для всех текстов длины два?
То есть
qw + we + er + rt =2.354+.2343+2.334 / 3 = 2.232 ?
Или что здесь имеется в виду?
Среднее отношение по многим текстам - сложить отношение всех текстов разной длины и найти среднее?

**Comment by ioannkozlitin** [comment]
Да, найти среднее по нескольким текстам заданной длины. Сколько их брать, - спросите Вы, - чем больше, тем лучше. Разумно взять хотя бы штук 30, а лучше - 100.

**Comment by saburovatory** [comment]
@ioannkozlitin 
В последнем комите сделан вывод среднего отношения. Только вопрос - как это поможет сориентироваться в выборе порога?

**Comment by saburovatory** [comment]
@ioannkozlitin 
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit
Иван Алексеевич, ссылка на документ,где выведен подсчет отношения правдоподобия

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, еще обновила версию теоретического обоснования, документ сохранила в проекте.

**Comment by ioannkozlitin** [comment]
Вика, что-то Вы куда-то пропали. Как Ваши успехи?

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, посмотрите, пожалуйста последние изменения по выводу дисперсии для отношения правдоподобия для определенной длины по количеству символов.
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit

При вычислении дисперсии для широфтекста исключены отрицательные значения, потому что если их оставить, то мы уже сразу можем сказать что он шифрованный (не рассматриваем буквосочетания, которых нет в исходном тексте).

Дисперсия (**именно для шифротекста**) получилось слишком большой....

**Comment by ioannkozlitin** [comment]
Надо все-таки оставить отрицательные значения. В этом вся соль.

**Comment by ioannkozlitin** [comment]
Иначе у Вас уже не Вальд, а что-то другое...

**Comment by ioannkozlitin** [comment]
Еще: лучше выводите не дисперсию, а стандартное отклонение.

**Comment by saburovatory** [comment]
@ioannkozlitin 
По правилу трех s аналогично как трех сигма?

**Comment by ioannkozlitin** [comment]
Стандартное отклонение - это квадратный корень из дисперсии

**Comment by ioannkozlitin** [comment]
А в чем Ваш вопрос, я что-то не понял...

**Comment by saburovatory** [comment]
Тогда я не правильно поняла изначально. Сейчас ОК, поняла, сделаю

**Comment by ioannkozlitin** [comment]
неправильно слитно пишется :)))

**Comment by saburovatory** [comment]
Исправлюсь :)

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич
1. Вернула нули
2. Вывод стандартного отклонения тоже добавила
3. Дописала все главы теоретического обоснования до второй главы
4. Вопрос : я не нашла где буквы не соответствуют друг другу, в плане. Вы говорили что величины у меня названы разными буквами. Но я буду еще раз все повторно вычитывать, дабы исключить ошибки.
5. Добавила список литературы. Мне есть его чем еще расширить. пока не вписала.
6. Как дальше действовать при описании алгоритма данной работы? сейчас остановилась на порогах в критерии Вальда.
7. что будет представлять из себя третья глава? В плане как необходимо нужно будет действовать.
8. В плане была часть про дерево решений и алгоритм случайного леса. Я включила туда небольшое описание, но не совсем поняла - он будет необходим при сравнении? 
9. Посмотрите, пожалуйста, описание алгоритма нашей работы, это Глава 2, часть 1, раздел 1.4.  Здесь мне необходимы Ваши комментарии.

**Comment by ioannkozlitin** [comment]
Файл с результатами сделайте, как Вы раньше делали.

**Comment by saburovatory** [comment]
@ioannkozlitin 
внесла результаты, но по - моему, что - то не так. Файл по той же ссылке
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit

**Comment by ioannkozlitin** [comment]
К средним вопросов нет; вопрос, почему везде d^2=1, странно...

**Comment by saburovatory** [comment]
@ioannkozlitin 
Это я забыла исправить, сделаю

**Comment by ioannkozlitin** [comment]
Насчет 3 главы и собственно ранд. лесов - дайте мне стандартные отклонения, средние. Я Вам напишу, как пороги ставить. Потом лесами займемся.

**Comment by ioannkozlitin** [comment]
Что касается текста, то там я вижу пока что собранный и немного структуированный Вами материал. Для построения связанного и логически выстроенного текста потребуется еще немало работы. Все что написано, в целом написано хорошо, но с логикой изложения и структурой есть проблемы. Еще: не увлекайтесь описанием тех аспектов теории, которыми Вы потом пользоваться не будете. Не в размере счастье.

**Comment by ioannkozlitin** [comment]
А какие Вам нужны комментарии по разделу 1.4 ?

**Comment by saburovatory** [comment]
@ioannkozlitin 
Ну среднее ведь и отклонение уже вывела, просто осталось опечатку в плане "d^2". Или чего - то не хватает?

**Comment by saburovatory** [comment]
> Все

 что написано, в целом написано хорошо, но с логикой изложения и структурой есть проблемы.

Вот поэтому и спрашивала комментарии по всему тексту, или хотя бы с первых частей, чтобы немного начать структурировать и логически выстраивать.

**Comment by ioannkozlitin** [comment]
Проблема не в том, что там d^2 написано, а что у Вас ВЕЗДЕ d^2 = 1, а это явная ошибка.

**Comment by ioannkozlitin** [comment]
Оптимально было бы Вам 1 раз прийти с текстом, и я бы Вам рассказал, как писать. А потом можно и удаленно.

**Comment by ioannkozlitin** [comment]
Думаю, минут за 15 мы бы управились.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Получается что там должно быть sqrt(d) = 1
Но отчего 1 я пока не знаю

**Comment by ioannkozlitin** [comment]
Добавил книгу Уберто Эко "Как написать дипломную работу". Книга написана гуманитарием для гуманитариев, но нам, технарям, тоже может быть полезна. Можете на ночь почитать, чтобы проникнуться тем, каким должен быть идеальный диплом.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Результаты исправила, залила на док файл
Жду комментариев по порогам
Простите,что так долго вышло по времени
Ошибка и правда была какая - то очень глупая
https://docs.google.com/document/d/1JMEw10jW038e9pPPwTR5eYgE0OdXtLp7eY6h6E5pHEo/edit

**Comment by saburovatory** [comment]
Там где "-nan"- очень маленькая дисперсия, поэтому так выводится
Дальше исправила на ноль

**Comment by ioannkozlitin** [comment]
Пусть n - число символов в тестируемом отрезке текста (см. Вашу таблицу)
mo(n), do(n) - мат. ожидание и стандартное отклонение для открытого текста
mc(n), dc(n) - мат. ожидание  и стандартное отклонение для шифрованного текста

Если dc(n) < 1, возьмем dc(n) = 1.

Верхний порог (если выше его - текст открытый) mo(n) - 3 * do(n)
Нижний порог (если меньше его - текст шифрованный) mc(n) + 3 * dc(n)

Вместо 3 можно взять 5 или даже 10. Чем больше это число, тем быстрее сработает критерий, но тем он ненадежнее.

Чем больше n, тем надежнее критерий, но тем дольше он работает. Можно выбрать для начала n = 3 и проверить критерий. Потом перебрать с помощью него ключи.

p.s. Книжку посмотрели?

**Comment by saburovatory** [comment]
@ioannkozlitin 
1) книгу начала смотреть
2) по порогам пройдусь завтра

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, я Вам направила письмо на почту. Посмотрите, пожалуйста.

**Comment by ioannkozlitin** [comment]
Пишите все сюда, т.к. телефон остался дома, а гугловская почта мне на работе не доступна.

**Comment by saburovatory** [comment]
Нам в пятницу поступило распоряжение подписать у дипломных руководителей отчеты и дневники практики - все то же самое, как и в прошлом семестре.
1) я Вам направляю свои документы на согласование
2) можем ли мы (точнее кто - то один из нас - я, Влад, Паша, Артем) - подойти к Вам на работу, чтобы подписать все у вас разом? Когда вам удобнее всего?
Документы прикреплю в обед, пока нет возможности.

**Comment by ioannkozlitin** [comment]
Пускай кто-нибудь из вас придет с 15.00 до 17.00

**Comment by saburovatory** [comment]
Завтра в это время можно?

**Comment by ioannkozlitin** [comment]
Мне все равно. В Москву я, вроде, завтра не еду.

**Comment by saburovatory** [comment]
@ioannkozlitin 
последний коммит - применение критерия

**Comment by ioannkozlitin** [comment]
Видел, теперь нужно делать перебор ключей

**Comment by ioannkozlitin** [comment]
А еще мне совершенно непонятно, как работает Ваш код...

**Comment by ioannkozlitin** [comment]
Избегайте вот такого: return new double[2]{sum, pow(sum2 - pow(sum,2), 0.5)};
Это не только ужасно читается, это еще и потенциально дает утечку памяти...
Вот здесь: info = find_limits(count, INPUT); Старый info затирается и выделенная ранее память теряется.

**Comment by saburovatory** [comment]
Каким образом организовать перебор?
Код постараюсь позже разъяснить ( если это нужно)
С ректором поняла, оптимизирую

**Comment by saburovatory** [comment]
@ioannkozlitin комментарии выше

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, столкнулась с такой проблемой у Вальда
k>mo(n) - 3 * do(n)
k<mc(n) + 3 * dc(n)
dc(n) получается очень большим числом, потому что у нас  в закрытом тексте есть запрещенные биграммы, которые сильно влияют на коэффициент правдоподобия
Получается что k ВСЕГДА меньше чем mc(n) + 3 * dc(n).
Варианты решения:
очевидно,что нужно избавиться от запрещенных биграмм при подсчете коэффициента правдоподобия закрытого текста
1) Можно искать такие наборы символов в закрытом тексте, чтобы среди них не встречалось запрещенных биграмм, НО для уже относительно небольшого числа символов сделать это невозможно (проверяла);
2) Реализовать шифрование без образования запрещенных биграмм.

Жду Ваших комментариев.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, каким образом организовать перебор ключей?

**Comment by saburovatory** [comment]
@ioannkozlitin 
В последнем коммите нет промежуточных файлов, практически в 10 раз работает быстрее.

**Comment by saburovatory** [comment]
@ioannkozlitin 
Иван Алексеевич, защиту поставили на 15 июня.
Предзащита в конце мая- июня (с датами пока неясно) возможно потребует вашего участия.

**Comment by ioannkozlitin** [comment]
понял

**Comment by saburovatory** [comment]
@ioannkozlitin 
Предзащиту поставили 24. Группа ратует о переносе даты пока, из - за большой разницы между датами
